<?php

namespace AppBundle\Repository;

/**
 * ReviewRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
